export const friendsScreenStrings = {
  title: 'Crew',
  pendingRequests: 'Pending Requests',
  crewTitle: 'Crew',
  allMembersLabel: 'All Crew Members',
  filters: {
    all: 'All',
    active: 'Active',
    rivals: 'Rivals',
  },
  emptyTitle: 'No crew members yet',
  emptySubtitle: 'Add people to your crew to challenge them!',
  rivalsEmptyTitle: 'No rivals yet',
  rivalsEmptySubtitle: 'Rival matchups will appear here once the feature is available.',
  findPeopleCta: 'Find People',
  challengeCta: 'Challenge',
  presenceLabel: 'Active',
  levelLabel: 'Level info soon',
  rivalryLabel: 'Rivals',
  suggestionsTitle: 'Suggestions',
  suggestionsSubtitle: 'People you may know',
  loadingMessage: 'Loading crew...',
  errorTitle: 'Could not load crew',
  addCrewCta: 'Add Crew',
  alerts: {
    genericTitle: 'Error',
    acceptFailed: 'Failed to accept request.',
    declineFailed: 'Failed to decline request.',
    sendFailed: 'Failed to send crew request.',
    requestSentTitle: 'Request Sent',
    requestSentMessage: 'Crew request sent successfully.',
    challengeComingSoon: 'Challenge flow is coming soon.',
    searchComingSoon: 'Crew search is coming soon.',
  },
} as const;

export const addFriendScreenStrings = {
  title: 'Add Crew',
  pageHeading: 'Grow Your Crew',
  pageSubtitle: 'Search by username or share your invite link with friends',
  shareInviteLinkTitle: 'Share Invite Link',
  shareInviteLinkSubtitle: 'Share The Battle Invite Link',
  linkLoading: 'Loading invite link…',
  linkUnavailable: 'Could not load invite link',
  copyButton: 'Copy',
  searchTitle: 'Search for Crew',
  searchSubtitle: 'Find people by username',
  searchPlaceholder: 'Enter username',
  searchButton: 'Search',
  searchingMessage: 'Searching...',
  emptyTitle: 'No users found',
  emptySubtitle: 'Try a different username',
  dividerLabel: 'OR',
  errors: {
    copyFailed: 'Could not copy to clipboard.',
    shareFailed: 'Could not open the share sheet.',
  },
  success: {
    copiedLink: 'Invite link copied.',
  },
  alerts: {
    genericTitle: 'Error',
    alreadySentTitle: 'Already Sent',
    alreadySentMessage: 'You already have a pending request with this user.',
    requestSentTitle: 'Crew Request Sent',
    requestSentMessage: (friendName: string) => `A crew request has been sent to ${friendName}.`,
  },
} as const;
