export const friendsScreenStrings = {
  title: 'Crew',
  pendingRequests: 'Pending Requests',
  crewTitle: 'Crew',
  allMembersLabel: 'All Crew Members',
  filters: {
    all: 'All',
    active: 'Active',
    rivals: 'Rivals',
  },
  emptyTitle: 'No crew members yet',
  emptySubtitle: 'Add people to your crew to challenge them!',
  rivalsEmptyTitle: 'No rivals yet',
  rivalsEmptySubtitle: 'Rival matchups will appear here once the feature is available.',
  findPeopleCta: 'Find People',
  challengeCta: 'Challenge',
  presenceLabel: 'Active',
  levelLabel: 'Level info soon',
  rivalryLabel: 'Rivals',
  suggestionsTitle: 'Suggestions',
  suggestionsSubtitle: 'People you may know',
  loadingMessage: 'Loading crew...',
  errorTitle: 'Could not load crew',
  addCrewCta: 'Add Crew',
  alerts: {
    genericTitle: 'Error',
    acceptFailed: 'Failed to accept request.',
    declineFailed: 'Failed to decline request.',
    sendFailed: 'Failed to send crew request.',
    requestSentTitle: 'Request Sent',
    requestSentMessage: 'Crew request sent successfully.',
    challengeComingSoon: 'Challenge flow is coming soon.',
    searchComingSoon: 'Crew search is coming soon.',
  },
} as const;

export const addFriendScreenStrings = {
  title: 'Add Crew',
  searchTitle: 'Search for Crew',
  searchSubtitle: 'Find people by username',
  searchPlaceholder: 'Enter username',
  searchButton: 'Search',
  searchingMessage: 'Searching...',
  emptyTitle: 'No users found',
  emptySubtitle: 'Try a different username',
  inviteTitle: 'Invite to Crew',
  inviteSubtitle: "Invite people who aren't on Legacy Battle yet",
  inviteViaTextTitle: 'Invite via Text Message',
  inviteViaTextSubtitle: 'Send an SMS invitation to your contacts',
  inviteViaEmailTitle: 'Invite via Email',
  inviteViaEmailSubtitle: 'Send an email invitation',
  dividerLabel: 'OR',
  alerts: {
    genericTitle: 'Error',
    alreadySentTitle: 'Already Sent',
    alreadySentMessage: 'You already have a pending request with this user.',
    requestSentTitle: 'Crew Request Sent',
    requestSentMessage: (friendName: string) => `A crew request has been sent to ${friendName}.`,
    emailUnavailable: 'Email is not available on this device.',
    emailOpenFailed: 'Could not open the email app.',
  },
  inviteMessage:
    'Hey! Join me on Legacy Battle - the ultimate sports prediction app! Download it here: [App Store Link]',
  inviteEmailSubject: 'Join me on Legacy Battle!',
  inviteEmailBody:
    "Hey!\n\nI've been using Legacy Battle to make sports predictions and challenge friends. You should join me!\n\nDownload the app here: [App Store Link]\n\nSee you on the battlefield!",
} as const;
